version: '3.4'

services:
  customerweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  productweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"




  orderweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

